version: 2
updates:
  # Cấu hình cho NPM (root folder)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 10 # Giảm từ 20 xuống 10 (đủ cho 2 nhóm update)
    
    # Gom nhóm các bản cập nhật
    groups:
      root-minor-and-patch: # Tên nhóm unique cho root
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      
      root-major: # Tên nhóm unique cho root
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "major"
      
      # root-security: # Nhóm riêng cho security updates
      #   applies-to: security-updates
      #   patterns:
      #     - "*"
    
    # Tùy chỉnh commit message
    commit-message:
      prefix: "root"
      prefix-development: "root(dev)"
      include: "scope"
    
    labels:
      - "root-side"
      - "dependencies"
      - "automated-pr"
    
    # Tự động rebase khi có conflict
    rebase-strategy: "auto"

  # Cấu hình cho NPM (server folder)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 10
    
    groups:
      server-minor-and-patch: # Tên nhóm unique cho server
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      
      server-major: # Tên nhóm unique cho server
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "major"
      
      # server-security: # Nhóm riêng cho security updates
      #   applies-to: security-updates
      #   patterns:
      #     - "*"
    
    commit-message:
      prefix: "server"
      prefix-development: "server(dev)"
      include: "scope"
    
    labels:
      - "server-side"
      - "dependencies"
      - "automated-pr"
    
    rebase-strategy: "auto"
