
version: 2
updates:
  # Cấu hình cho NPM (root folder)
  - package-ecosystem: "npm" # Dự án NodeJS/NextJS
    directory: "/"
    schedule:
      interval: "daily"

    # Cho phép tất cả loại phụ thuộc
    allow:
      - dependency-type: "all"

    # Giới hạn số PR được mở lên là 20
    open-pull-requests-limit: 20
    # Gom nhóm các bản cập nhật thường và bảo mật:
    groups:
      minor-and-patch-updates: # Nhóm 1: Chỉ các bản cập nhật Minor và Patch
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      major-updates: # Nhóm 2: Chỉ các bản cập nhật Major
        applies-to: version-updates
        update-types:
          - "major"
    # Gán nhãn rõ ràng cho ecosystem
    labels:
      - "root-side"
      - "dependencies"
      - "automated-pr"

  # Cấu hình cho NPM (server folder)
  - package-ecosystem: "npm" # Dự án NodeJS/NextJS
    directory: "/server"
    schedule:
      interval: "daily"

    # Cho phép tất cả loại phụ thuộc
    allow:
      - dependency-type: "all"

    # Giới hạn số PR được mở lên là 20
    open-pull-requests-limit: 20
    groups:
      minor-and-patch-updates: # Nhóm 1: Chỉ các bản cập nhật Minor và Patch
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      major-updates: # Nhóm 2: Chỉ các bản cập nhật Major
        applies-to: version-updates
        update-types:
          - "major"
    # Gán nhãn rõ ràng cho ecosystem
    labels:
      - "server-side"
      - "dependencies"
      - "automated-pr"
    
